FROM alpine:3.10 as qemu

ARG QEMU_VERSION=4.2.0-6
ARG QEMU_ARCHS="s390x"

RUN apk --update add curl

# Enable non-native runs on amd64 architecture hosts
RUN for i in ${QEMU_ARCHS}; do curl -L https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-${i}-static.tar.gz | tar zxvf - -C /usr/bin; done
RUN chmod +x /usr/bin/qemu-*

FROM s390x/ubuntu:18.04
COPY --from=qemu /usr/bin/qemu-*-static /usr/bin/